package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private Button btnElec2025;

	// Event Listener on Button[#btnElec2025].onAction
	@FXML
	public void btnAdvance(ActionEvent event) {
		// TODO Autogenerated
	}
}
